### PR TITLE
added dockerfile and did various changes

### PR DESCRIPTION
**Pull request by rishvantsingh**
1 - Added docker file for the project.
2 - There are many changes that you need to do at the code level.
3 - Meanwhile you can merge it.Please review and merge it.

### CODE REVIEW

**Comment by rishvantsingh** [comment]
If in future there will be any changes ill will do it.

**Review by ehsandeep — COMMENTED** [review]
```console
docker build -t test .
[+] Building 18.0s (9/9) FINISHED                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 172B                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                        3.1s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                          0.0s
 => [internal] load build context                                                                                                                                      2.2s
 => => transferring context: 6.80MB                                                                                                                                    2.1s
 => CACHED [1/4] FROM docker.io/library/ubuntu:20.04@sha256:b5a61709a9a44284d88fb12e5c48db0409cfad5b69d4ff8224077c57302df9cf                                           0.0s
 => [2/4] COPY . .                                                                                                                                                    12.4s
 => [3/4] WORKDIR /src/app/                                                                                                                                            0.0s
 => ERROR [4/4] RUN sudo chmod +x entrypoint.sh                                                                                                                        0.2s
------
 > [4/4] RUN sudo chmod +x entrypoint.sh:
#9 0.208 /bin/sh: 1: sudo: not found
------
executor failed running [/bin/sh -c sudo chmod +x entrypoint.sh]: exit code: 127
```

@rishvantsingh could you add more details on building and running the application with docker?

**Comment by rishvantsingh** [comment]
See this dockerfile is good to go but you will have to change the dependency with the latest and then it will work fine.You can merge it and update you project code and then if there will be any change then i lll do it.

**Comment by ehsandeep** [comment]
Please see - https://github.com/projectdiscovery/interactsh-web#using-docker

**Pull request closed without merging**
