### PR TITLE
fix missing authorization token

### PR DESCRIPTION
**Pull request by NS-Sp4ce**

### CODE REVIEW

**Review by ehpankaj — COMMENTED** [review]
Hey, thanks for contributing to this project.

I reviewed the changes you made. It turns out that you have added auth token in 2 places

- First in `customHost` -> `deleteHost` function.
The way in which function works is that when you delete a custom host, interactsh switches back to its default i.e public interactsh server which does not require any auth token to register.
- Second one is in a function which runs only when a user is visiting interact client for first time or when there is no previously registered instance available. In that case, it registers on default interactsh server which again does not require any auth token.

Let me know if I've missed any point or could you clarify why this changes are required?

**Comment by NS-Sp4ce** [comment]
> Hey, thanks for contributing to this project.
> 
> I reviewed the changes you made. It turns out that you have added auth token in 2 places
> 
> * First in `customHost` -> `deleteHost` function.
>   The way in which function works is that when you delete a custom host, interactsh switches back to its default i.e public interactsh server which does not require any auth token to register.
> * Second one is in a function which runs only when a user is visiting interact client for first time or when there is no previously registered instance available. In that case, it registers on default interactsh server which again does not require any auth token.
> 
> Let me know if I've missed any point or could you clarify why this changes are required?

When i run my `interactsh` backend server with `-token` param ,front-end program(`interactsh-web`) get `401 authentication error` and dispaly `Server Unavailable` ,and can not enter any token parameters anywhere ,even i set token param in `src/pages/homePage/index.tsx` or `src/components/customHost/index.tsx` ,when i review the code ,i see
https://github.com/projectdiscovery/interactsh-web/blob/6f1c437e005023b248f72711b7488845ec11f4e7/src/components/customHost/index.tsx#L100
https://github.com/projectdiscovery/interactsh-web/blob/6f1c437e005023b248f72711b7488845ec11f4e7/src/pages/homePage/index.tsx#L236
the `register` function passed an empty token parameter,and in 
https://github.com/projectdiscovery/interactsh-web/blob/6f1c437e005023b248f72711b7488845ec11f4e7/src/lib/index.ts#L173
in this line ,here is a judgement which `header` param to use.

**Comment by ehsandeep** [comment]
@NS-Sp4ce 

> front-end program(interactsh-web) get 401 authentication error and dispaly `Server Unavailable`

In the case of 401, a pop-up screen appears to submit token instead of `Server Unavailable` error, in the case of `Server Unavailable` error, with the following PR https://github.com/projectdiscovery/interactsh-web/pull/23 we can update interactsh server from the top menu, so not sure if this change is required, otherwise please create an issue detailing the problem you are experiencing before we make any new changes.

**Comment by NS-Sp4ce** [comment]
> @NS-Sp4ce
> 
> > front-end program(interactsh-web) get 401 authentication error and dispaly `Server Unavailable`
> 
> In the case of 401, a pop-up screen appears to submit token instead of `Server Unavailable` error, in the case of `Server Unavailable` error, with the following PR #23 we can update interactsh server from the top menu, so not sure if this change is required, otherwise please create an issue detailing the problem you are experiencing before we make any new changes.

when user set customer `host` and `token` in `src/components/customHost/index.tsx` which dispaly `Server Unavailable`
image

**Comment by ehsandeep** [comment]
Closing the PR as the changes are unclear if it's required or not, pleases create a GitHub issue detailing the problem you look to address so we can discuss further and make the changes if required.

**Pull request closed without merging**
